---
abstract: "Catalyst plugin to initialize Log::Log4perl from the application's configuration"
author:
  - 'jason hord <pravus@cpan.org>'
build_requires:
  Catalyst::Runtime: 5.80
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Plugin-Log-Log4perl
no_index:
  directory:
    - inc
    - t
requires:
  Log::Log4perl: 0
  Moose: 0
  namespace::autoclean: 0
resources:
  license: http://opensource.org/licenses/mit-license.php
version: 0.01
